# -*- coding: utf-8 -*-
"""task1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUSuARGGkcVI7Y5XrhbXuXabVuxlg3Nt
"""

!pip install pandas matplotlib seaborn

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


url = '/content/sample_data/API_SP.POP.TOTL_DS2_en_csv_v2_38144.csv'

# Remove the tab separator as the data seems to be comma-separated
df = pd.read_csv(url, skiprows=4)


print("Sample Data:")
display(df.head())


print("\nAvailable Columns:")
print(df.columns)

# Identify year columns and population columns
year_cols = [col for col in df.columns if col.isdigit()]
# Assuming the population is in the year columns
population_cols = year_cols

# Plot distribution of the first few year columns as an example
if year_cols:
    plt.figure(figsize=(12, 8))
    # Plotting the distribution of values in the first few year columns as a proxy for year distribution
    # This is not a true year distribution plot, but shows the data spread across years
    df[year_cols[:10]].melt().pipe((sns.histplot, "data"), x="value", bins=20, kde=True, color='skyblue')
    plt.title('Distribution of Population Values Across Early Years')
    plt.xlabel('Population')
    plt.ylabel('Frequency')
    plt.grid(True)
    plt.show()
else:
    print("\nNo year columns found. Please check available columns and adjust the code.")


# Plot distribution of population data across all available year columns
if population_cols:
    plt.figure(figsize=(12, 8))
    # Melting the DataFrame to have all population data in one column for plotting
    df[population_cols].melt().pipe((sns.histplot, "data"), x="value", bins=50, kde=True, color='lightgreen')
    plt.title('Population Distribution (Across All Years)')
    plt.xlabel('Population')
    plt.ylabel('Frequency')
    plt.grid(True)
    plt.show()
else:
    print("\nNo population columns found. Please check available columns and adjust the code.")