# -*- coding: utf-8 -*-
"""task2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GUSuARGGkcVI7Y5XrhbXuXabVuxlg3Nt
"""

!pip install pandas matplotlib seaborn

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('titanic')

print("🔍 Basic Information")
print(df.info())
print("\n🧾 Summary Statistics:")
print(df.describe(include='all'))

print("\n❗ Missing Values:")
print(df.isnull().sum())

df.drop(['deck'], axis=1, inplace=True)

df['age'].fillna(df['age'].median(), inplace=True)

df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)

df.dropna(subset=['embarked', 'embark_town'], inplace=True)

plt.figure(figsize=(6, 4))
sns.countplot(x='survived', data=df, palette='pastel')
plt.title('Survival Count')
plt.xlabel('Survived (0 = No, 1 = Yes)')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df['age'], bins=30, kde=True, color='skyblue')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(x='sex', hue='survived', data=df, palette='Set2')
plt.title('Survival by Gender')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(6, 4))
sns.countplot(x='pclass', hue='survived', data=df, palette='Set1')
plt.title('Survival by Passenger Class')
plt.ylabel('Count')
plt.xlabel('Passenger Class')
plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()


print("\n✅ EDA Completed Successfully!")